import React from 'react';

function Home(props) {
    return (
        <div>
            <h2 style={{color:"red"}}>Home Component</h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Autem eaque fugit blanditiis, tempora nihil laborum ratione illo eos saepe quibusdam quia corrupti velit nobis alias aspernatur enim in. Quidem autem ducimus vel voluptatibus. Nostrum consequatur, enim pariatur numquam eum sint quaerat non, voluptatum deserunt aspernatur temporibus laudantium, perferendis cum eius iste dolorem nulla tempora corporis fugit qui? Inventore corrupti illo odio commodi vero repellat aliquid eligendi harum blanditiis aliquam enim voluptate consequuntur quibusdam repellendus porro autem consequatur, ullam facere quisquam! Omnis labore a aspernatur error architecto, non voluptates fugiat vel, et facere mollitia illum sapiente reprehenderit quam ratione. Non quaerat nam minima asperiores mollitia aspernatur, veniam blanditiis voluptate rem aut nulla quasi exercitationem incidunt excepturi dolores fuga labore delectus doloremque illum fugit placeat deleniti itaque odio? Atque ducimus quia deleniti id, vel in illum mollitia autem eum nihil repudiandae explicabo. Illo perferendis quisquam a iusto libero unde reiciendis omnis amet officiis optio! Consectetur ipsam sapiente expedita? Culpa error in dolor, sequi quod et ratione. Suscipit nemo id illo harum esse quibusdam in, ullam corrupti itaque ab aut necessitatibus excepturi nobis deserunt, rerum laboriosam autem praesentium ipsa? Sit, quibusdam soluta. Quibusdam, quae cum possimus, sapiente iusto repellendus aperiam corrupti maxime placeat necessitatibus repudiandae temporibus similique, vel distinctio. Recusandae cupiditate et dicta harum? At ea ipsam, perferendis id voluptate doloremque culpa expedita nesciunt optio, temporibus eos, beatae iusto quae! Quibusdam non qui aliquid unde quos beatae voluptate ullam vel dolore nostrum quo odio, neque aspernatur velit corrupti maiores facilis laudantium veritatis! Voluptas, voluptates magni. Aliquam quisquam dolores soluta ab voluptatibus quia, tempore laboriosam ut dignissimos quod laudantium, unde fugit! Iste consequatur cumque dolorum quaerat dolores fugit obcaecati magnam eligendi repudiandae eveniet unde enim fugiat cupiditate autem beatae quibusdam dolor totam, quo distinctio! Alias repudiandae fuga corrupti amet voluptates aspernatur fugit exercitationem consequuntur?</p>
        </div>
    );
}

export default Home;